using System;
using System.Web.UI.WebControls;
using System.Diagnostics;
using System.IO;

namespace TweetDis
{
	public class LocationData
	{
		public static readonly string[] SINGLE_WORD_LOCATIONS = {
		"dago",
		"cisitu",
		"gasibu",
		"pasteur",
		"cihampelas",
		"ciwalk",
		"antapani",
		"lodaya",
		"palasari",
		"cilangkarang",
		"mamisi",
		"cigagak",
		"pangaritan",
		"cipadung",
		"setiabudi",
		"panyileukan",
		"panglawungan",
		"gedebage",
		"cipamokolan",
		"cigending",
		"nagrog",
		"cijambe",
		"cisaranten",
		"dirgantara",
		"cisaranten",
		"margahayu",
		"ciwastra",
		"kawaluyaan",
		"sekejati",
		"ciparay",
		"pindad",
		"kebonjayanti",
		"cijawura",
		"parakan",
		"batununggal",
		"cimuncang",
		"padasuka",
		"sukatma",
		"jatihandap",
		"cikadur",
		"cibatu",
		"kaliati",
		"pamanukan",
		"cikutra",
		"pahlawan",
		"bekamin",
		"cisadea",
		"serang",
		"lebak",
		"karawang",
		"gumuruh",
		"turangga",
		"salendro",
		"citamiang",
		"cikaso",
		"cipandan",
		"cisaga",
		"mendong",
		"ciharit",
		"cigondewah",
		"bojong",
		"cibuntu",
		"cibolerang",
		"borobudur",
		"kopo",
		"cibaduyut",
		"caringin",
		"karasak",
		"kurdi",
		"sriwijaya",
		"parakan",
		"suryalaya",
		"cijagra",
		"kliningan",
		"waas",
		"golek",
		"karawitan",
		"pabaki",
		"maksudi",
		"panjunan",
		"sukarma",
		"tugu",
		"kencana",
		"katip",
		"otista",
		"adikasi",
		"pungkur",
		"ciateul",
		"pasundan",
		"nyengseret",
		"samsudin",
		"surogala",
		"srimahi",
		"sruajaya",
		"sancang",
		"melong",
		"sadakeling",
		"burangrang",
		"cikawao",
		"karapitan",
		"betok",
		"jongjolong",
		"cilentah",
		"beunteur",
		"tripang",
		"ciremay",
		"cerme",
		"durmo",
		"maskumambang",
		"pangkur",
		"kinanti",
		"asmi",
		"umar",
		"subrata",
		"pangumpaan",
		"galunggung",
		"emong",
		"emur",
		"eceng",
		"genjer",
		"kangkung",
		"patuha",
		"kemandilan",
		"cikuray",
		"halimun",
		"cijerah",
		"holis",
		"muncang",
		"nawawi",
		"andir",
		"jamika",
		"jambal",
		"gabus",
		"peda",
		"pagarsih",
		"kondektur",
		"onong",
		"citepus",
		"sereh",
		"irsad",
		"cibadak",
		"saritem",
		"klenteng",
		"kebonjati",
		"waringin",
		"pepetan",
		"serat",
		"ayang",
		"ciroyom",
		"katalina",
		"paledang",
		"ayidia",
		"udowo",
		"pendawa",
		"tumaritis",
		"srikandi",
		"subrada",
		"purabaya",
		"samiaji",
		"pamoyanan",
		"dursasana",
		"pajajaran",
		"nakula",
		"sadewa",
		"pandu",
		"baladewa",
		"korawa",
		"durna",
		"sukajadi",
		"cipedes",
		"bungur",
		"sarimanah",
		"sarijadi",
		"tonggoh",
		"lamdeuh",
		"cipaku",
		"hegarmanah",
		"damar",
		"boshcah",
		"ciumbuleuit",
		"menjangan",
		"cigadung",
		"cikondang",
		"sangkuriang",
		"cisitu",
		"kidang",
		"siliwangi",
		"pasteur",
		"rotgen",
		"westoff",
		"sukiman",
		"ganesa",
		"skanda",
		"hasanudin",
		"dipatiukur",
		"surapati",
		"wirayuda",
		"titiran",
		"tekukur",
		"japati",
		"puter",
		"jalak",
		"dederuk",
		"puyuh",
		"gagak",
		"gereja",
		"rajawali",
		"trunojoyo",
		"tirtayasa",
		"bahurekso",
		"cipayung",
		"sulanjana",
		"purnawarman",
		"kornel",
		"aceh",
		"sumbawa",
		"ambon",
		"sumatera",
		"jawa",
		"jakarta",
		"antapani",
		"abc",
		"braga",
		"naripan",
		"sunda",
		"banceuy",
		"veteran",
		"merdeka",
		"supratman",
		"cicendo",
		"lembong",
		"cihampelas",
		"bandung"};

		public static readonly string[] MULTIPLE_WORD_LOCATIONS = {"ds. cisurupan",
		"ds. pasir wangi",
		"ds. pasir jati",
		"komplek perumahan cilengkrang",
		"negla sari",
		"ds. pasi biru",
		"kpmplek perumahan bumi wijaya kusuma permai",
		"komplek perumahan cipadung permai",
		"desa cipadung",
		"embah jaksa",
		"komplek perumahan cipadung indah",
		"cipadung indah",
		"komplek perumahan bumi panyileukan",
		"mekar mulya",
		"cisaranten kidul",
		"ds. derwati",
		"silih asih",
		"bumi asih",
		"komplek perumahan sentosa asih jaya",
		"komplek perumahan riung bandung",
		"ds. cigending",
		"kaum kulon",
		"raya ujung berung",
		"sumber sari",
		"komplek perumahan panghegar",
		"ds. mekar mulya",
		"ds. ujung berung",
		"rumah sakit",
		"komplek perumahan ujung berung",
		"komplek perumahan sukur baru",
		"sukur baru",
		"ds. pasir endah",
		"komplek perumahan taruna parahyangan",
		"ds. sindang jaya",
		"suka asih",
		"ds. cisaranten bina harapan",
		"perumnas islamic centre",
		"ds. karang pamulang",
		"karang pamulang",
		"sindang laya",
		"pasir putih",
		"simpang sari",
		"pacuan kuda",
		"saharjo sari endah",
		"rusadi sh",
		"mekar sari",
		"ds. suka miskin",
		"arcamanik indah",
		"golf timur",
		"golf timur i-ix",
		"bulu tangkis",
		"sepak bola",
		"tenis meja",
		"terjun payung",
		"sel.air.l.indah",
		"komplek perumahan golf garden estate",
		"golf barat",
		"golf barat i-iv",
		"atl i-x",
		"tanah makadam",
		"komplek perumahan guruminda",
		"komplek perumahan metro soekarno-hatta estate",
		"komplek perumahan sanggar hurip estate",
		"sgr kencana utama",
		"komplek perumahan margahayu raya",
		"venus raya",
		"tata surya",
		"anca bolang",
		"ds. sekejati",
		"komplek perumahan viva getsemani estate",
		"cidurian selatan",
		"cidurian utara",
		"cidurian baru",
		"palem raya",
		"cijawura girang",
		"marta cinta",
		"pasir pogor",
		"bunga bakung",
		"batu permata",
		"ds. kujang sari",
		"ters.kiaracondong",
		"warunh jambu",
		"psm dalam",
		"babakan sari",
		"mbah malim",
		"babakan surabaya",
		"jembatan opat",
		"buah batu",
		"komplek perumahan lands estate cicaheum",
		"jend.a.yani",
		"babakan h.tamin",
		"ds. mandala jati",
		"raya sindang laya",
		"komplek perumahan arga arcamanik",
		"komplek perumahan pratista antapani estate",
		"pratista barat",
		"pratista raya",
		"pratista timur i-v",
		"komplek perumahan bougenvile estate",
		"ters.jakarta",
		"penghulu kh.hasan mustafa",
		"simpang pahlawan",
		"komplek perumahan land estate cikutra baru",
		"suka senang",
		"awi tali",
		"awi temeh",
		"awi gombong",
		"awi bitung",
		"jati negara",
		"wiranta textil",
		"rangkas bitung",
		"kebon gedang",
		"binong jati",
		"gatot subroto",
		"ranca goong",
		"ranca belut",
		"ranca tengah",
		"ranca wangi",
		"jl ranca wangi i-v",
		"komplek perumahan eka bhakti gumuruh",
		"batu kencana",
		"raja mantri wetan",
		"bandung selatan",
		"ds. gempol sari",
		"gempol sari",
		"bumi asri",
		"komplek perumahan melong green garden",
		"wijaya kusuma",
		"ds. cigondewah",
		"ters.pasir koja",
		"pasir koja",
		"ds. cigondewah rahayu",
		"komplek perumahan cibuntu",
		"sumber sugih",
		"sumber sari",
		"sumber mukti",
		"sumber endah",
		"sumber nanjung",
		"komplek perumahan sumber sari indah",
		"dian moleh",
		"ds. margahayu utara",
		"komplek perumahan holis indah",
		"komplek perumahan endah sandang",
		"komplek perumahan taman kopo indah",
		"komplek perumahan nata endah",
		"komplek perumahan kopo permai",
		"komplek perumahan taman cibaduyut indah",
		"ds. cibaduyut wetan",
		"komplek perumahan cibaduyut permai",
		"komplek perumahan kopo elok",
		"ds. cirangrang",
		"ds. cibaduyut kidul",
		"ds. marga suka",
		"ds. cibaduyut",
		"komplek perumahan mekar wangi",
		"mekar harum",
		"komplek perumahan eka bhaki leuwi panjang",
		"leuwi panjang",
		"kebon lega",
		"komplek perumahan land estate leuwi panjang",
		"komplek perumahan panca bhakti",
		"karasak utara",
		"karasak utara ii",
		"moh.toha",
		"kembar i-iii",
		"kembar timur",
		"pasir luyu timur",
		"pasir galam",
		"pasir jaya",
		"pasir jaya i-vi",
		"mengger girang",
		"pasir mas",
		"pasir luyu",
		"ds. menger",
		"parakan asri",
		"parakan indah",
		"komplek perumahan eka bhakti suryalaya",
		"suryalaya i-iii",
		"st.cileunca",
		"st.lembang",
		"st.patenggang",
		"buah batu",
		"raja mantri",
		"kayu agung",
		"guntur sari",
		"guntur sari i-iii",
		"komplek perumahan puteraco indah",
		"wartawan i-iii",
		"kuli kulu",
		"olos tomo",
		"candra wulan",
		"komplek perumahan sakura indah",
		"taman sakura",
		"bojong loa",
		"lio genteng",
		"bapa rasdan",
		"bapa suhaya",
		"lingkar selatan",
		"babakan tarogong",
		"komplek perumahan kopo kencana",
		"komplek perumahan citarip",
		"citarip kulon",
		"citarip tengah",
		"citarip kidul",
		"citarip wetan",
		"siti munigar",
		"tegal lega",
		"astana anyar",
		"jam hari",
		"pelindung hewan",
		"komplek perumahan tegal permata indah",
		"sindang pala",
		"sawah kurung",
		"moch.ramdan",
		"sri gadis",
		"sri tunggal",
		"ancol kawung",
		"ancol babat",
		"lauk emas",
		"buah batu",
		"pelajar pejuang 45",
		"telaga bodas",
		"melong kidul",
		"melong kaler",
		"tangkuban perahu",
		"raa marta negara",
		"asmara dana",
		"renggong manis",
		"guntur madu",
		"sekar tonggerat",
		"sekar tonggerat i-iii",
		"komplek perumahan lingkar selatan",
		"srimalin baru",
		"kembar utara",
		"kembar urip",
		"kembar sari",
		"kembar tengah",
		"kembar tengah i-ii",
		"pasir malang",
		"pasir malang i-vii",
		"pasir luyu timur",
		"lengkong tengah",
		"taman siswa",
		"sasak gantung",
		"bandung barat",
		"komplek perumnas cijerah",
		"h.alfi",
		"nana rochana",
		"ters.suryani",
		"situ aksan",
		"suka pakir",
		"suka haji",
		"nata wijaya",
		"h.sapari",
		"minyak tanah",
		"rajawali timur",
		"laks.muda nurtanio",
		"rajawali barat",
		"komplek perumahan land estate dadali",
		"sri gunting selatan",
		"gunung batu",
		"babakan.cianjur",
		"raya cimindi",
		"komplek perumahan cendrawasih",
		"burung tungku",
		"maleber barat",
		"maleber utara",
		"rajawali i-iii",
		"gg. giwanan",
		"kom.udara supadio",
		"dr.abd.r.saleh",
		"gedung sembilan",
		"gedung delapan",
		"astina citra yuda",
		"suka lilah",
		"letn.ud.subagio",
		"kapten sumantri",
		"beeng sempani",
		"letkol panji saleh",
		"suka sari",
		"lmu. suparmin",
		"suka warna baru",
		"dr.djudjunan",
		"suka mulya",
		"babakan jeruk",
		"ters.babakan jeruk",
		"suka mulya indah",
		"komplek perumahan suka karya",
		"sekar mekar",
		"sekar sari",
		"suka galih",
		"surya sumantri",
		"suka karya",
		"setra indah",
		"karang tanjung",
		"cipedes tengah",
		"karang arum",
		"setra jaya",
		"setra sari",
		"sari madu",
		"ir.sutami",
		"sari wangi",
		"suka warna",
		"lemah keundeut",
		"komplek perumnas sarijadi",
		"sari asih",
		"sari endah",
		"geger hegar",
		"jl geger sari",
		"geger sari i-vi",
		"geger subur",
		"geger kalong hilir",
		"geger kalong",
		"sersan sodik",
		"geger kalong tengah",
		"setia budi",
		"budi asih",
		"komplek perumahan budi asih",
		"komplek perumahan land estate budi sari",
		"budi indah",
		"sindang sirna",
		"karang anyar",
		"kebun manggu",
		"bandung utara",
		"cidadap girang",
		"ds. ledeng",
		"kapt.abd.hamid",
		"bukit raya",
		"kapt.tendean",
		"apidaks tubun",
		"karang sari",
		"suka maju",
		"jujur mulya",
		"sabar tenterem",
		"pabrik daging",
		"ki putih",
		"gunung agung",
		"gunung kreumbi",
		"ranca bentang",
		"gunung putri",
		"gunung batur",
		"bukit tunggul",
		"bukit jarian",
		"bukit dago utara",
		"bukit dago selatan",
		"dago elos",
		"tubagus ismail",
		"sadang serang",
		"cukang kawung",
		"cikutra barat",
		"komplek perumahan sadang serang",
		"sumur bandung",
		"dayang sumbi",
		"prof. eyckman",
		"dr. saleh",
		"dr. slamet",
		"dr. otten",
		"dr. rajiman",
		"rumah sakit",
		"dr. cipto",
		"ehrig curic",
		"taman sari",
		"ciung wanara",
		"munding laya",
		"gelap nyawang",
		"raden patah",
		"tengku umar",
		"surya kencana",
		"imam bonjol",
		"kyai gede utama",
		"pager gunung",
		"h. hasan",
		"bangus rangin",
		"sentot ali syah bana",
		"bangga dempul",
		"wira angun-angun",
		"sultan agung",
		"harian bangga",
		"gajah lumantung",
		"sawung galing",
		"rangga malela",
		"raman hewan",
		"maulana yusup",
		"prabudi nuntur",
		"arya jipang",
		"adipati k. bumu",
		"kalipah apo",
		"jend.a.yani",
		"asia afrika",
		"r.e martadinata",
		"kebon kawung",
		"dalem kawung",
		"wastu kencana",
		"pasir kaliki"};

		private static string[] allLocationsCache;

		public static string[] ALL_LOCATIONS {
			get {
				if (allLocationsCache == null) {
					allLocationsCache = new string[SINGLE_WORD_LOCATIONS.Length + MULTIPLE_WORD_LOCATIONS.Length];
					SINGLE_WORD_LOCATIONS.CopyTo (allLocationsCache, 0);
					MULTIPLE_WORD_LOCATIONS.CopyTo (allLocationsCache, SINGLE_WORD_LOCATIONS.Length);
				}
				return allLocationsCache;
			}
		}

		private static TypoCorrector locTCCache;
		public static TypoCorrector LOCATION_TYPOCORRECTOR {
			get {
				if (locTCCache == null) {
					InitializeLocTC();
				}

				return locTCCache;
			}
		}

		public static void InitializeLocTC() {
			locTCCache = new TypoCorrector(SINGLE_WORD_LOCATIONS);
		}






	}
}
